using DevExpress.Utils.Filtering.Internal;
using DevExpress.Xpf.Grid;

namespace TestExample.Infrastructure.Localizers
{
    public class CustomerGridControlLoaclizer : GridControlLocalizer
    {
        protected override void PopulateStringTable()
        {
            base.PopulateStringTable();
            //AddString(GridControlStringId.MenuColumnBestFit, Resource.GridControlLocalizer.MenuColumnBestFit);
            //AddString(GridControlStringId.MenuColumnBestFitColumns, Resource.GridControlLocalizer.MenuColumnBestFitColumns);
            //AddString(GridControlStringId.MenuColumnSortAscending, Resource.GridControlLocalizer.MenuColumnSortAscending);
            //AddString(GridControlStringId.MenuColumnSortDescending, Resource.GridControlLocalizer.MenuColumnSortDescending);
            //AddString(GridControlStringId.PopupFilterAll, Resource.GridControlLocalizer.PopupFilterAll);
            //AddString(GridControlStringId.GridGroupPanelText, Resource.GridControlLocalizer.GridGroupPanelText);
            //AddString(GridControlStringId.MenuColumnShowSearchPanel, Resource.GridControlLocalizer.MenuColumnShowSearchPanel);
            //AddString(GridControlStringId.MenuColumnHideSearchPanel, Resource.GridControlLocalizer.MenuColumnHideSearchPanel);
            //AddString(GridControlStringId.MenuColumnClearSorting, Resource.GridControlLocalizer.MenuColumnClearSorting);
            //AddString(GridControlStringId.MenuColumnShowGroupPanel, Resource.GridControlLocalizer.MenuColumnShowGroupPanel);
            //AddString(GridControlStringId.MenuColumnHideGroupPanel, Resource.GridControlLocalizer.MenuColumnHideGroupPanel);
            //AddString(GridControlStringId.MenuColumnGroup, Resource.GridControlLocalizer.MenuColumnGroup);
            //AddString(GridControlStringId.PopupFilterBlanks, Resource.GridControlLocalizer.PopupFilterBlanks);
            //AddString(GridControlStringId.ExcelColumnFilterPopupClearFilter, Resource.GridControlLocalizer.ExcelColumnFilterPopupClearFilter);
            //AddString(GridControlStringId.ExcelColumnFilterPopupEnterValue, Resource.GridControlLocalizer.ExcelColumnFilterPopupEnterValue);
            //AddString(GridControlStringId.ExcelColumnFilterPopupFilterRulesTabCaption, Resource.GridControlLocalizer.ExcelColumnFilterPopupFilterRulesTabCaption);
            //AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullText, Resource.GridControlLocalizer.ExcelColumnFilterPopupSearchNullText);
            //AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullTextAll, Resource.GridControlLocalizer.ExcelColumnFilterPopupSearchNullTextAll);
            //AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullTextDate, Resource.GridControlLocalizer.ExcelColumnFilterPopupSearchNullTextDate);
            //AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullTextMonth, Resource.GridControlLocalizer.ExcelColumnFilterPopupSearchNullTextMonth);
            //AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullTextYear, Resource.GridControlLocalizer.ExcelColumnFilterPopupSearchNullTextYear);
            //AddString(GridControlStringId.ExcelColumnFilterPopupSelectDate, Resource.GridControlLocalizer.ExcelColumnFilterPopupSelectDate);
            //AddString(GridControlStringId.ExcelColumnFilterPopupSelectValue, Resource.GridControlLocalizer.ExcelColumnFilterPopupSelectValue);
            //AddString(GridControlStringId.ExcelColumnFilterPopupValuesTabCaption, Resource.GridControlLocalizer.ExcelColumnFilterPopupValuesTabCaption);
            AddString(GridControlStringId.CellPeerName, "{2}, Item: {0}, Column Display Index: {1}");
            AddString(GridControlStringId.GridGroupPanelText, "拖动列标题到此处,根据该列分组");
            AddString(GridControlStringId.GridGroupRowDisplayTextFormat, "{0}: {1}");
            AddString(GridControlStringId.ErrorWindowTitle, "错误");
            AddString(GridControlStringId.InvalidRowExceptionMessage, "你想要更正这个值吗？");
            AddString(GridControlStringId.GridOutlookIntervals, "更早;上个月;早于当前月;三个星期前;二个星期前;上星期;;;;;;;;昨天;今天;明天;;;;;;;;下星期;二个星期后;三个星期后;一个月后;下月;下个月之后;");
            AddString(GridControlStringId.DefaultGroupSummaryFormatString_Count, "计数={0}");
            AddString(GridControlStringId.DefaultGroupSummaryFormatString_Min, "{1}最小值是{0}");
            AddString(GridControlStringId.DefaultGroupSummaryFormatString_Max, "{1} 最大值是 {0}");
            AddString(GridControlStringId.DefaultGroupSummaryFormatString_Avg, "Avg of {1} is {0:0.##}");
            AddString(GridControlStringId.DefaultGroupSummaryFormatString_Sum, "Sum of {1} is {0:0.##}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatStringInSameColumn_Count, "计数={0}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatStringInSameColumn_Min, "最小值={0}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatStringInSameColumn_Max, "最大值={0}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatStringInSameColumn_Avg, "平均值={0:0.##}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatStringInSameColumn_Sum, "和={0:0.##}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatString_Count, "计数={0}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatString_Min, "Min of {1} is {0}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatString_Max, "Max of {1} is {0}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatString_Avg, "Avg of {1} is {0:0.##}");
            AddString(GridControlStringId.DefaultTotalSummaryFormatString_Sum, "Sum of {1} is {0:0.##}");
            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatStringInSameColumn_Count, "计数={0}");
            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatStringInSameColumn_Min, "最小值={0}");
            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatStringInSameColumn_Max, "最大值={0}");
            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatStringInSameColumn_Avg, "平均值={0:0.##}");
            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatStringInSameColumn_Sum, "和={0:0.##}");

            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatString_Count, "计数={0}");
            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatString_Min, "Min of {1} is {0}");
            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatString_Max, "Max of {1} is {0}");
            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatString_Avg, "Avg of {1} is {0:0.##}");
            AddString(GridControlStringId.DefaultGroupColumnSummaryFormatString_Sum, "Sum of {1} is {0:0.##}");
            AddString(GridControlStringId.PopupFilterAll, "(全部)");
            AddString(GridControlStringId.PopupFilterBlanks, "(空白)");
            AddString(GridControlStringId.PopupFilterNonBlanks, "(非空白)");
            AddString(GridControlStringId.ColumnChooserCaption, "列选择器");
            AddString(GridControlStringId.ColumnBandChooserCaption, "自定义");
            AddString(GridControlStringId.ColumnChooserCaptionForMasterDetail, "{0}: Column Chooser");
            AddString(GridControlStringId.ColumnChooserDragText, "Drag a column here to customize layout");
            AddString(GridControlStringId.BandChooserDragText, "Drag a band here to customize layout");
            AddString(GridControlStringId.ColumnBandChooserColumnsTabCaption, "列");
            AddString(GridControlStringId.ColumnBandChooserBandsTabCaption, "Bands");
            AddString(GridControlStringId.GridNewRowText, "点击此处添加新行");
            AddString(GridControlStringId.ExcelColumnFilterPopupValuesTabCaption, "值过滤");
            AddString(GridControlStringId.ExcelColumnFilterPopupFilterRulesTabCaption, "高级");
            AddString(GridControlStringId.ExcelColumnFilterPopupClearFilter, "清除过滤");
            AddString(GridControlStringId.ExcelColumnFilterPopupFilterBetweenFrom, "从: ");
            AddString(GridControlStringId.ExcelColumnFilterPopupFilterBetweenTo, "到: ");
            AddString(GridControlStringId.AddCurrentSelectionToFilter, "将当前选择项添加到筛选");
            AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullText, "搜索");
            AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullTextAll, "搜索 (全部)");
            AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullTextYear, "搜索 年");
            AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullTextMonth, "搜索 月");
            AddString(GridControlStringId.ExcelColumnFilterPopupSearchNullTextDate, "搜索 日");
            AddString(GridControlStringId.ExcelColumnFilterPopupEnterValue, "输入一个值...");
            AddString(GridControlStringId.ExcelColumnFilterPopupSelectValue, "选中一个值...");
            AddString(GridControlStringId.ExcelColumnFilterPopupSelectDate, "输入日期...");
            AddString(GridControlStringId.MenuGroupPanelFullCollapse, "全部折叠");
            AddString(GridControlStringId.MenuGroupPanelFullExpand, "全部展开");
            AddString(GridControlStringId.MenuGroupPanelClearGrouping, "清除分组");
            AddString(GridControlStringId.MenuColumnSortAscending, "升序排序");
            AddString(GridControlStringId.MenuColumnSortDescending, "降序排序");
            AddString(GridControlStringId.MenuColumnSortBySummaryAverage, "平均值");
            AddString(GridControlStringId.MenuColumnSortBySummaryCount, "计数");
            AddString(GridControlStringId.MenuColumnSortBySummarySum, "和");
            AddString(GridControlStringId.MenuColumnSortBySummaryMax, "最大值");
            AddString(GridControlStringId.MenuColumnSortBySummaryMin, "最小值");
            AddString(GridControlStringId.MenuColumnSortBySummaryAscending, "升序");
            AddString(GridControlStringId.MenuColumnSortBySummaryDescending, "降序");
            AddString(GridControlStringId.MenuColumnClearSorting, "清除排序");
            AddString(GridControlStringId.MenuColumnUnGroup, "取消分组");
            AddString(GridControlStringId.MenuColumnGroup, "按此列分组");
            AddString(GridControlStringId.MenuColumnShowGroupPanel, "显示分组面板");
            AddString(GridControlStringId.MenuColumnHideGroupPanel, "隐藏分组面板");
            AddString(GridControlStringId.MenuColumnGroupInterval, "分组间隔");
            AddString(GridControlStringId.MenuColumnGroupIntervalNone, "无");
            AddString(GridControlStringId.MenuColumnGroupIntervalDay, "天");
            AddString(GridControlStringId.MenuColumnGroupIntervalMonth, "月");
            AddString(GridControlStringId.MenuColumnGroupIntervalYear, "年");
            AddString(GridControlStringId.MenuColumnGroupIntervalSmart, "最小");
            AddString(GridControlStringId.MenuColumnResetGroupSummarySort, "Clear Summary Sorting");
            AddString(GridControlStringId.MenuColumnSortGroupBySummaryMenu, "依据汇总排序");
            AddString(GridControlStringId.MenuColumnGroupSummarySortFormat, "{1} 按 '{0}' - {2}");
            AddString(GridControlStringId.MenuColumnGroupSummaryEditor, "分组汇总编辑器...");
            AddString(GridControlStringId.MenuColumnShowColumnChooser, "Show Column Chooser");
            AddString(GridControlStringId.MenuColumnHideColumnChooser, "Hide Column Chooser");
            AddString(GridControlStringId.MenuColumnShowColumnBandChooser, "Show Column/Band Chooser");
            AddString(GridControlStringId.MenuColumnHideColumnBandChooser, "Hide Column/Band Chooser");
            AddString(GridControlStringId.MenuColumnBestFit, "自动调整列宽度");
            AddString(GridControlStringId.MenuColumnBestFitColumns, "自动调整所有列宽度");
            AddString(GridControlStringId.MenuColumnUnboundExpressionEditor, "Expression Editor...");
            AddString(GridControlStringId.MenuColumnClearFilter, "清除过滤");
            AddString(GridControlStringId.MenuColumnFilterEditor, "过滤编辑器...");
            AddString(GridControlStringId.MenuColumnFixedStyle, "Fixed Style");
            AddString(GridControlStringId.MenuColumnFixedNone, "无");
            AddString(GridControlStringId.MenuColumnFixedLeft, "左");
            AddString(GridControlStringId.MenuColumnFixedRight, "右");
            AddString(GridControlStringId.MenuColumnShowSearchPanel, "显示搜索面板");
            AddString(GridControlStringId.MenuColumnHideSearchPanel, "隐藏搜索面板");
            AddString(GridControlStringId.MenuFooterSum, "和");
            AddString(GridControlStringId.MenuFooterMax, "最大值");
            AddString(GridControlStringId.MenuFooterMin, "最小值");
            AddString(GridControlStringId.MenuFooterCount, "计数");
            AddString(GridControlStringId.MenuFooterAverage, "平均值");
            AddString(GridControlStringId.MenuFooterCustom, "自定义");
            AddString(GridControlStringId.MenuFooterCustomize, "自定义...");
            AddString(GridControlStringId.MenuFooterRowCount, "显示行数");
            AddString(GridControlStringId.GroupSummaryEditorFormCaption, "Group Summaries");
            AddString(GridControlStringId.TotalSummaryEditorFormCaption, "总数'{0}'");
            AddString(GridControlStringId.TotalSummaryPanelEditorFormCaption, "View Totals");
            AddString(GridControlStringId.SummaryEditorFormItemsTabCaption, "Items");
            AddString(GridControlStringId.SummaryEditorFormOrderTabCaption, "Order");
            AddString(GridControlStringId.SummaryEditorFormOrderLeftSide, "Left side:");
            AddString(GridControlStringId.SummaryEditorFormOrderRightSide, "Right side:");
            AddString(GridControlStringId.SummaryEditorFormOrderAndAlignmentTabCaption, "Order and Alignment");
            AddString(GridControlStringId.SummaryEditorFormMoveItemUpCaption, "Up");
            AddString(GridControlStringId.SummaryEditorFormMoveItemDownCaption, "Down");
            AddString(GridControlStringId.FilterEditorTitle, "Filter Editor");
            AddString(GridControlStringId.FilterPanelCaptionFormatStringForMasterDetail, "{0} filter:");
            AddString(GridControlStringId.GroupPanelDisplayFormatStringForMasterDetail, "{0}:");
            AddString(GridControlStringId.ProgressWindowTitle, "加载数据");
            AddString(GridControlStringId.ProgressWindowCancel, "取消");
            AddString(GridControlStringId.ErrorPanelTextFormatString, "Error occurred during processing server request ({0})");
            AddString(GridControlStringId.SummaryItemsSeparator, ", ");
            AddString(GridControlStringId.InvalidValueErrorMessage, "无效值");
            AddString(GridControlStringId.CheckboxSelectorColumnCaption, "选中项");
            AddString(GridControlStringId.GridCardExpandButtonTooltip, "Expand a card");
            AddString(GridControlStringId.GridCardCollapseButtonTooltip, "Collapse a card");
            AddString(GridControlStringId.NavigationMoveFirstRow, "First");
            AddString(GridControlStringId.NavigationMovePrevPage, "Previous Page");
            AddString(GridControlStringId.NavigationMovePrevRow, "Previous");
            AddString(GridControlStringId.NavigationMoveNextRow, "Next");
            AddString(GridControlStringId.NavigationMoveNextPage, "Next Page");
            AddString(GridControlStringId.NavigationMoveLastRow, "Last");
            AddString(GridControlStringId.NavigationAddNewRow, "Append");
            AddString(GridControlStringId.NavigationDeleteFocusedRow, "删除");
            AddString(GridControlStringId.NavigationEditFocusedRow, "编辑");
            AddString(GridControlStringId.NavigationRecord, "Record {0} of {1}");
            AddString(GridControlStringId.DateFiltering_ShowAllFilterName, "显示全部");
            AddString(GridControlStringId.DateFiltering_FilterBySpecificDateFilterName, "Filter by a specific date");
            AddString(GridControlStringId.DateFiltering_PriorToThisYearFilterName, "Prior to this year");
            AddString(GridControlStringId.DateFiltering_EarlierThisYearFilterName, "Earlier this year");
            AddString(GridControlStringId.DateFiltering_EarlierThisMonthFilterName, "Earlier this month");
            AddString(GridControlStringId.DateFiltering_LastWeekFilterName, "Last week");
            AddString(GridControlStringId.DateFiltering_EarlierThisWeekFilterName, "Earlier this week");
            AddString(GridControlStringId.DateFiltering_YesterdayFilterName, "昨天");
            AddString(GridControlStringId.DateFiltering_TodayFilterName, "今天");
            AddString(GridControlStringId.DateFiltering_TomorrowFilterName, "明天");
            AddString(GridControlStringId.DateFiltering_LaterThisWeekFilterName, "Later this week");
            AddString(GridControlStringId.DateFiltering_NextWeekFilterName, "Next week");
            AddString(GridControlStringId.DateFiltering_LaterThisMonthFilterName, "Later this month");
            AddString(GridControlStringId.DateFiltering_LaterThisYearFilterName, "Later this year");
            AddString(GridControlStringId.DateFiltering_BeyondThisYearFilterName, "Beyond this year");
            AddString(GridControlStringId.DateFiltering_BeyondFilterName, "Beyond");
            AddString(GridControlStringId.DateFiltering_ThisWeekFilterName, "This week");
            AddString(GridControlStringId.DateFiltering_ThisMonthFilterName, "This month");
            AddString(GridControlStringId.DateFiltering_EarlierFilterName, "Earlier");
            AddString(GridControlStringId.DateFiltering_EmptyFilterName, "空");
            AddString(GridControlStringId.DDExtensionsAddRows, "增加行");
            AddString(GridControlStringId.DDExtensionsCannotDropHere, "Cannot drop here");
            AddString(GridControlStringId.DDExtensionsDraggingMultipleRows, "Dragging {0} rows");
            AddString(GridControlStringId.DDExtensionsDraggingOneRow, "Dragging 1 row:");
            AddString(GridControlStringId.DDExtensionsInsertAfter, "Insert after row:");
            AddString(GridControlStringId.DDExtensionsInsertBefore, "Insert before row:");
            AddString(GridControlStringId.DDExtensionsMoveToChildrenCollection, "Move to children collection:");
            AddString(GridControlStringId.DDExtensionsMoveToGroup, "移动分组：");
            AddString(GridControlStringId.DDExtensionsRow, "行");
            AddString(GridControlStringId.EditForm_UpdateButton, "更新");
            AddString(GridControlStringId.EditForm_CancelButton, "取消");
            AddString(GridControlStringId.EditForm_Modified, "Your data is modified. Do you want to save the changes?");
            AddString(GridControlStringId.EditForm_Cancel, "Do you want to cancel editing?");
            AddString(GridControlStringId.EditForm_Warning, "警告");
            AddString(GridControlStringId.MenuRowFixedTop, "头部");
            AddString(GridControlStringId.MenuRowFixedNone, "无");
            AddString(GridControlStringId.MenuRowFixedBottom, "底部");
            
        }
    }
}
